### ISSUE TITLE
Accelerator readme doesn't give useful examples of acceleration

### ISSUE THREAD

**Issue by rcrogers** [kschiess/parslet#145] opened 2015-11-25 00:51 UTC
https://github.com/kschiess/parslet/blob/9afeb3ca5ce7f83786f9a78cb5dca06a199b29f3/qed/accelerators.md#bindings-and-actions

Not sure if this is an oversight or just unfinished, but I couldn't find an example of how an accelerator can actually speed up parsing, e.g. an example implementation of `GobbleUp`.  Will it always involve creating a custom `Atom` class?

These would also be useful:
- how to find hot spots
- approximate performance numbers (for an example scenario)
- an example where an accelerator's rule-matching capability has an advantage over just referencing custom atoms in the parser (`GobbleUp` appears to be a 1-to-1 substitution that doesn't make the parser substantially "dirtier")

**Comment by rcrogers** [comment] 2015-11-25 16:46
I found `GobbleUp`: https://github.com/kschiess/parslet/blob/66e242841ea27554a64f42d52093c1f41bc56e1e/qed/applique/gobbleup.rb

But I don't think the doc does a good idea of explaining what's possible with accelerator atoms.  Does it all boil down to finding a faster `StringScanner` method?

**Comment by kschiess** [comment] 2015-12-17 08:01
Honestly, I've ran into a design roadblock with accelerators - and have let it rest since then. The issue is that we want to support lazy evaluation across rule barriers - and that collides with acceleration. 

The most potential for speeding up parsers I see in creating custom 'partial' parsers aka atom classes. But if you really need to go fast - don't use ruby. Simple as that.

**Comment by rcrogers** [comment] 2015-12-23 23:05
All good to know, thanks for the response!

**Comment by kschiess** [comment] 2016-05-09 07:11
Welcome! (closing this)

**Closed by kschiess** 2016-05-09 07:11 UTC
Labels: discussion
